### PR TITLE
move NaturalDocs to tools folder. add reformat.bat to reformat code v…

### PR DESCRIPTION
**Pull request by Shoelace**
move NaturalDocs to tools folder.
add reformat.bat to reformat code via sqldeveloper.
check in reformatted code

### CODE REVIEW

**Comment by Pazus** [comment]
I think path to sql developer should be passed as parameter, could you change that?

**Comment by Shoelace** [comment]
Yes. Can/will do. I just they that together and committed it before I left the office.

On Thu, Jul 21, 2016 at 6:12 PM +0100, "Pazus" <notifications@github.com<mailto:notifications@github.com>> wrote:

I think path to sql developer should be passed as parameter, could you change that?

**Comment by Pazus** [comment]
@Shoelace could you your changes for current state and maybe create a PR to the main repo?

**Comment by Shoelace** [comment]
i'll redo as a request to main repo.. closing

**Pull request closed without merging**
